export const UPDATE_CITY = 'UPDATE_CITY'
export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const UPDATE_SECTOR = 'UPDATE_SECTOR'
export const UPDATE_SALARY_MIN = 'UPDATE_SALARY_MIN'
export const UPDATE_SALARY_MAX = 'UPDATE_SALARY_MAX'
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'

export const UPDATE_EMPLOYMENTYPE = 'UPDATE_EMPLOYMENTYPE'